# Generated by Django 5.2.1 on 2025-05-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.IntegerField()),
                ('patient_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('dob', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('husband_name', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField()),
                ('appointment_date', models.IntegerField()),
                ('appointment_time', models.IntegerField()),
                ('allocate_doctor', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
