# Generated by Django 5.2.1 on 2025-05-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.IntegerField()),
                ('patient_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('dob', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('husband_name', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='address',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='allocate_doctor',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='husband_name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='patient_code',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='patient_name',
        ),
    ]
