# Generated by Django 5.2.1 on 2025-05-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_biodata_mobile_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='biodata',
            new_name='client',
        ),
    ]
